// flow-typed signature: 081ed6fe5595d41410720eed11c691ff
// flow-typed version: <<STUB>>/gulp-sourcemaps_v^1.6.0/flow_v0.33.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gulp-sourcemaps'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'gulp-sourcemaps' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'gulp-sourcemaps/index' {
  declare module.exports: $Exports<'gulp-sourcemaps'>;
}
declare module 'gulp-sourcemaps/index.js' {
  declare module.exports: $Exports<'gulp-sourcemaps'>;
}
